version: "4.3"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_ngcash
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin.ngcash
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ngcash
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: ngcash_container
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local